/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Crawler crawler = new SingleThreadedCrawler();
        crawler.crawl("https://spring.io");
    }
}
